# Generated by Django 6.0.5 on 2026-05-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servico_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='horario_domingo',
            field=models.CharField(blank=True, default='Fechado', max_length=50, verbose_name='Domingo'),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='horario_quarta',
            field=models.CharField(blank=True, default='09:00 - 19:00', max_length=50, verbose_name='Quarta-feira'),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='horario_quinta',
            field=models.CharField(blank=True, default='09:00 - 19:00', max_length=50, verbose_name='Quinta-feira'),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='horario_sabado',
            field=models.CharField(blank=True, default='09:00 - 17:00', max_length=50, verbose_name='Sábado'),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='horario_segunda',
            field=models.CharField(blank=True, default='Fechado', max_length=50, verbose_name='Segunda-feira'),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='horario_sexta',
            field=models.CharField(blank=True, default='09:00 - 19:00', max_length=50, verbose_name='Sexta-feira'),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='horario_terca',
            field=models.CharField(blank=True, default='09:00 - 19:00', max_length=50, verbose_name='Terça-feira'),
        ),
    ]
