# Generated by Django 6.0.5 on 2026-05-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_barbeiro_horario_domingo_barbeiro_horario_quarta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbeiro',
            name='horario_domingo',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='horario_quarta',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='horario_quinta',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='horario_sabado',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='horario_segunda',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='horario_sexta',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='horario_terca',
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='avaliacao',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='horarios_trabalho',
            field=models.TextField(blank=True, default='Seg a Sex: 09:00 - 19:00\nSáb: 09:00 - 17:00'),
        ),
    ]
