# Generated by Django 4.2.11 on 2026-05-18 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(default='Barbeiro', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipe/')),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Barbeiro',
                'verbose_name_plural': 'Barbeiros',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoBarbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Minha Barbearia', max_length=100)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('foto_hero', models.ImageField(blank=True, null=True, upload_to='barbearia/')),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_numero', models.CharField(blank=True, help_text='Ex: 5584999999999', max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Configuração da Barbearia',
                'verbose_name_plural': 'Configurações da Barbearia',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracao_minutos', models.PositiveIntegerField(default=30)),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone (ex: bi-scissors)', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='galeria/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('destaque', models.BooleanField(default=False)),
                ('barbeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='core.barbeiro')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Fotos da Galeria',
                'ordering': ['-destaque', '-data_upload'],
            },
        ),
    ]
